from .user_regster import users_register_router
from .master_register import masters_register_router
from .masters_catalog import masters_catalog_router, build_master_detail_kb
from .order_master import order_master_router
from .create_service import create_service_router
from .create_order import create_order_router
from .check_new_order_master import check_new_order_router
from .select_action_order import select_action_order_router
from .services_actions_for_master import services_actions_router